### PR TITLE
doc(contact-manager-tutorial): fix layout issue in bootstrap v4

### PR DESCRIPTION
**Pull request by 3cp**
When this tutorial was upgraded from bootstrap v3 to v4, the layout is not quite right.
1. the left contact list is only clickable on the text, not the whole item.
2. the form layout is incorrect, leaving right side a blank gap.
3. some font size is too big, might due to bootstrap changes.
The updated code can be reviewed lively at https://gist.dumber.app/?gist=da1297fe5662ce31911cf5cb2bdce960
Also updated router config to use pushState.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Any particular reason to also enable push state? I'm not opposed to it, just not sure if we need to add an explanation in the tutorial related to that.

**Comment by 3cp** [comment]
I am not sure why it's not enabled in the tutorial, probably because it was created long ago.

The tutorial now uses aurelia-cli to build, the default webpack skeleton has proper `<base href="/">` in the html head.

I think current users would expect a framework using push state. I will add some explanation.

**Comment by 3cp** [comment]
dumber-gist embedded browser back/forward buttons only support pushState based routing, because it monkey-patches pushState and replaceState.

**Comment by EisenbergEffect** [comment]
Thanks!

**Pull request merged**
