### PR TITLE
Make description of name conversions more prominent

### PR DESCRIPTION
**Pull request by xamm**
Since Aurelia changes the names of certain elements this should be better described to make it easier for beginners to get started.

This PR is meant to be a first draft and I would like to get feedback and start a discussion on how the name conversions could be more clear for beginners.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
We're definitely open to this kind of improvement. The funny thing is, I can't recall if our site's Markdown parser can handle bolded inline code 🤣 If there's an issue I can edit it later though. Let me know when you feel that you've got this PR where you want it. Thanks for contributing! If you are passionate about documentation, we're looking for more help on our Aurelia 2 docs, which we've recently started on. Let me know.

**Comment by xamm** [comment]
I just looked through the documentation and it seems like bolded lines are possible.

[Link to Binding basics](https://raw.githubusercontent.com/aurelia/documentation/master/current/en-us/4.%20binding/1.%20basics.md)

There is the line which includes a bolded word:
> * `one-time`: flows data one direction, from the view-model to the view, **once**.

**Comment by xamm** [comment]
Sorry for the late response. But I think the changed documentation in the PR is quite consistent  and could be merged.

**Comment by xamm** [comment]
> We're definitely open to this kind of improvement. The funny thing is, I can't recall if our site's Markdown parser can handle bolded inline code 🤣 If there's an issue I can edit it later though. Let me know when you feel that you've got this PR where you want it. Thanks for contributing! 

Sorry for the late response. But I think the changed documentation in the PR is quite consistent and could be merged.

>If you are passionate about documentation, we're looking for more help on our Aurelia 2 docs, which we've recently started on. Let me know.

I have no experience with Aurelia 2 but am willing to help with documentation or maybe implementations.

**Comment by EisenbergEffect** [comment]
@xamm Thanks again for the contribution. If you are interested in helping us with the Aurelia 2 docs, you will find them in the `docs` folder of our Aurelia 2 monorepo: https://github.com/aurelia/aurelia The docs are in an early state, with most of the content not yet present, but you are welcome to provide feedback on what we do have. I'm working on porting and re-arranging our old content now. Once that done we'll start filling in the gaps, and that would be a great opportunity to do some writing if you are interested.

**Pull request merged**
