### PR TITLE
docs(documentation/French) - French translation.

### PR DESCRIPTION
**Pull request by RomainLanz**
Hi everyone,

This translation is not finished yet. I have created this PR to avoid duplication of translation. So please, to every french people who want to start a translation in french, send a PR to my fork.

I will continue to translate this documentation on my free time.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Thanks for helping out @RomainLanz ! Would you mind signing our CLA? https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1

**Comment by RomainLanz** [comment]
It is you that I thank for all your work you made.

I have read it, approved it and signed it!

**Comment by EisenbergEffect** [comment]
Thanks. Just let me know when you feel the translation is ready to merge.

**Comment by EisenbergEffect** [comment]
I noticed that you are working mostly on the docs.md file. I would recommend working on the get-started.md file first. It's shorter and usually of more immediate value.

**Comment by RomainLanz** [comment]
Sure. I think that docs.md is going to be changed also?

I'll focus my work on get-started.md and try to finish the traduction of this file for the end of this week-end.

**Comment by EisenbergEffect** [comment]
I'm going to close this PR for now. If/when you do a full translation of either the get started guide or the docs, just send a PR and I'll be happy to merge it in. Thanks!

**Pull request closed without merging**
