### PR TITLE
Add documentation for Docker builds

### PR DESCRIPTION
**Pull request by shahabganji**
In this PR, I am trying to add some documentation to indicate how it is possible to dockerize Aurelia application.

cc/ @EisenbergEffect

### CODE REVIEW

**Comment by shahabganji** [comment]
@EisenbergEffect I just wanted to ping you to let you know this is done, if you think I should change something please let me know.

**Comment by EisenbergEffect** [comment]
Excellent. Thank you @shahabganji I'll try to review it this weekend. We've recently had a flurry of very exciting activity around Aurelia, so my backlog very quickly expanded. I may not get to it right away, but I'll try. If you don't see this get merged in the next day or two, feel free to bug 😄

**Comment by shahabganji** [comment]
@EisenbergEffect I should have let you know earlier but I thought if I only remove the `WIP` you might have got notified so didn't want to double ping 😄

And good to hear about activities around Aurelia, do you think I could be of any help?

**Comment by EisenbergEffect** [comment]
Thanks for the offer @shahabganji Unfortunately, most of what has landed on my plate, only I can do. It's all good but just might delay a full review of this by a day or two.

**Comment by EisenbergEffect** [comment]
I had a few extra minutes between tasks, so I gave it a review and was able to merge. I'll also have our technical writer look at this. Thanks for working on our docker support and documenting it!

**Pull request merged**
