### PR TITLE
Added recipe to workaround readonly attribute set by TFS

### PR DESCRIPTION
**Pull request by lorond**
https://github.com/aurelia/cli/pull/1034#issuecomment-461190661

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Thanks @lorond ! I'm sure this will be useful for the community.

**Comment by huochunpeng** [comment]
@EisenbergEffect you probably need to double check and do the `${` escaping before publishing new doc.

**Comment by EisenbergEffect** [comment]
@huochunpeng Oops! I'll make a note to fix before publishing.

**Comment by EisenbergEffect** [comment]
This should be fine since it's all within a codeblock, I believe.

**Pull request merged**
