### PR TITLE
Document the defaultValidationTrigger config option

### PR DESCRIPTION
**Pull request by RomkeVdMeulen**
See aurelia-validation release 1.6.0

### CODE REVIEW

**Comment by RomkeVdMeulen** [comment]
Paging @bigopon for review since you were oversaw this feature on https://github.com/aurelia/validation/pull/536

**Comment by bigopon** [comment]
Arr man i wish we could be this consistent about doc. Looks good to me. Thanks @RomeVdMeulen 
@EisenbergEffect

**Comment by EisenbergEffect** [comment]
Awesome! Thank you @RomkeVdMeulen !
@Sayan751 Do we have this in the new au2 validation implementation and docs?

**Comment by Sayan751** [comment]
@EisenbergEffect Yup, already in place :) I am yet to write the docs though. Postponing that as the validation plugin is still work in progress and there are quite a few moving parts.

**Pull request merged**
