### PR TITLE
fixed:  The type of http should be HttpClient.

### PR DESCRIPTION
**Pull request by HIRANO-Satoshi**
Hi,

I found a minor typo in the example of TypeScript and fixed it.

We decided to use Aurelia. We support you.

Best,

Hirano Satoshi

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Would you mind signing our CLA? https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1

**Comment by HIRANO-Satoshi** [comment]
Sure. I finished.

I think Aurelia is the best now because of its simple use. Maybe the architecture and concept of Aurelia are more sophisticated than others.

Thank you very much for your long effort!! 

Hirano Satoshi

**Comment by EisenbergEffect** [comment]
Thank you for helping us to improve our docs! Also, I want to introduce you to @davismj (Matt Davis) I'm not sure if you two have met online, but Matt is a member of our core team who is hoping to move to Japan in the near future. Perhaps you two can connect?

**Comment by HIRANO-Satoshi** [comment]
Rob,

Thanks for introduction. I've just received an email from Matt. We will welcome him and we could provide some help if he lives near us.

If he visits us (A national institute called AIST, 1 hour from Tokyo), I can show him how we use Aurelia.

Is it possible to use Polymer 1.0 with Aurelia? Polymer 1.0 has much more components than MaterializeCSS. Polymer 1.0 is a bit too complicated to use for me. I prefer Aurelia.

I have spent some days for the following configuration. Thrift is an RPC which supports 10+ languages and it can generate TypeScript d.ts files. I think it's much better than REST.

Google App Engine -> Apache Thirft -> Aurelia+TypeScript +(MaterializeCSS or Polymer 1.0?)
                                                           -> iOS  (Swift, Objective-C), Android

We write DB schema in Thrift IDL and compile it with our H_GTX into Python classes representing DataStore schema on App Engine as well as communication stubs for JS, Objective-C, and etc. 
A single declarative schema definition serves all clients and the server.

I'm facing to a quite big JS job and I'm quite new to JS. Only Aurelia is my hope.

Write to happy.hirano at gmail.com for further personal things.

Hirano Satoshi

**Comment by EisenbergEffect** [comment]
Great to hear! Yes, you can use Polymer together with Aurelia, no problem.
I just answered a question related to this. Here's the issue with the
details: https://github.com/aurelia/binding/issues/103

On Thu, Jun 4, 2015 at 9:30 PM, HIRANO Satoshi <notifications@github.com>
wrote:

> Rob,
>
> Thanks for introduction. I've just received an email from Matt. We will
> welcome him and we could provide some help if he lives near us.
>
> If he visits us (A national institute called AIST, 1 hour from Tokyo), I
> can show him how we use Aurelia.
>
> Is it possible to use Polymer 1.0 with Aurelia? Polymer 1.0 has much more
> components than MaterializeCSS. Polymer 1.0 is a bit too complicated to use
> for me. I prefer Aurelia.
>
> I have spent some days for the following configuration. Thrift is an RPC
> which supports 10+ languages and it can generate TypeScript d.ts files. I
> think it's much better than REST.
>
> Google App Engine -> Apache Thirft -> Aurelia+TypeScript +(MaterializeCSS
> or Polymer 1.0?)
> -> iOS (Swift, Objective-C), Android
>
> We write DB schema in Thrift IDL and compile it with our H_GTX into Python
> classes representing DataStore schema on App Engine as well as
> communication stubs for JS, Objective-C, and etc.
> A single declarative schema definition serves all clients and the server.
>
> I'm facing to a quite big JS job and I'm quite new to JS. Only Aurelia is
> my hope.
>
> Write to happy.hirano at gmail.com for further personal things.
>
> Hirano Satoshi
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/documentation/pull/101#issuecomment-109118447>
> .
>



-- 
Rob Eisenberg,
President - Blue Spire
www.durandaljs.com

**Comment by HIRANO-Satoshi** [comment]
Thanks Rob. Great news. I will try.

Hirano Satoshi

**Pull request merged**
